# Generated by Django 4.1.3 on 2022-11-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('dt_nascimento', models.DateField()),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
