# Generated by Django 4.1.3 on 2022-11-14 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='senha',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
