# Generated by Django 4.1.3 on 2022-11-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuariomodel_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuariomodel',
            name='login',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
