name: Django-React-App

on:
  push:
    branches: master

  env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
    DB_NAME: ${{ secrets.DB_NAME }}
    DB_USER: ${{ secrets.DB_USER }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    DB_HOST: ${{ secrets.DB_HOST }}
    DB_PORT: ${{ secrets.DB_PORT }}
    DBT_NAME: ${{ secrets.DBT_NAME }}
    DBT_USER: ${{ secrets.DBT_USER }}
    DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
    DBT_HOST: ${{ secrets.DBT_HOST }}
    DBT_PORT: ${{ secrets.DBT_PORT }}

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Running tests
        run: |
          python manage.py test --keepdb
          
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} 
          heroku_email: ${{secrets.EMAIL}}
          dontautocreate: true